version: "3"
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
